version: '3'
services:
  database:
    image: "postgres:alpine"
    ports: 
        - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "gottado"
  app:
    image: "archiezgg/gottado"
    ports: 
      - "3000:3000"
    restart: always
    depends_on:
      - database
    links:
      - database